import './theme-config.css';
import './globals.css';
import '@radix-ui/themes/styles.css';
import { Container, Theme } from '@radix-ui/themes';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Navbar from './Navbar';
import AuthProvider from './_auth/Provider';
import { PropsWithChildren } from 'react';
import QueryClientProvider from './QueryClientProvider';

const inter = Inter({ subsets: ['latin'], variable: '--font-inter', display: 'swap' });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }: PropsWithChildren) {
	return (
		<html lang='en'>
			<body className={inter.variable}>
				<QueryClientProvider>
					<AuthProvider>
						<Theme accentColor='violet' grayColor='slate' radius='small'>
							<Navbar />
							<main className='p-5'>
								<Container>{children}</Container>
							</main>
						</Theme>
					</AuthProvider>
				</QueryClientProvider>
			</body>
		</html>
	);
}
